### ISSUE TITLE
You are talking about Fortigate templates... but the name of template is Juniper :)

### ISSUE THREAD

**Issue by bench81** [larcorba/Larcorba-Zabbix-templates-Fortigate-General-SNMPv3#3]
You are talking about Fortigate templates... but the name of template is Juniper :)
I think there is a little mistake :)
But we are dealing with the same vendors 👍

**Comment by nwildner** [comment]
Hey @larcorba . Any clue why you template references JunOS appliances when it should be a Fortigate template?

**Comment by larcorba** [comment]
Hi!

My brain must have been sleeping when I exported these :) I will upload the correct ones a.s.a.p.

**Comment by larcorba** [comment]
I've just fixed the issue! Enjoy
